# Generated by Django 6.1 on 2026-08-14 20:59

import uuid

import django.db.models.deletion
from django.db import migrations, models

import django_connectors._uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_object_id",
                    models.CharField(max_length=255, verbose_name="owner id"),
                ),
                (
                    "authorized_by_object_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("provider", models.CharField(max_length=100)),
                ("auth_backend", models.CharField(max_length=100)),
                ("auth_reference", models.CharField(blank=True, max_length=500)),
                ("auth_metadata", models.JSONField(blank=True, default=dict)),
                ("external_account_id", models.CharField(blank=True, max_length=255)),
                ("external_tenant_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending setup"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "setup_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_by_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="authorised by type",
                    ),
                ),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="owner type",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection",
                "verbose_name_plural": "connections",
                "ordering": ("-created_at",),
                "permissions": (("test_connection", "Can test a connection"),),
            },
        ),
        migrations.CreateModel(
            name="Binding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Registered source key.", max_length=150
                    ),
                ),
                ("resources", models.JSONField(blank=True, default=list)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "landing_key",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("poll_interval", models.DurationField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("min_run_interval", models.DurationField(blank=True, null=True)),
                ("run_timeout", models.DurationField(blank=True, null=True)),
                ("webhook_enabled", models.BooleanField(default=False)),
                ("dirty", models.BooleanField(default=False)),
                (
                    "landing_retention",
                    models.CharField(
                        choices=[
                            ("current_state", "Current state only"),
                            ("permanent", "Permanent"),
                        ],
                        default="current_state",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending first run"),
                            ("active", "Active"),
                            ("needs_review", "Needs review"),
                            ("blocked", "Blocked"),
                            ("disabled", "Disabled"),
                            ("purging", "Purging"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("landing_schema", models.JSONField(blank=True, default=dict)),
                (
                    "landing_schema_version_hash",
                    models.CharField(blank=True, max_length=100),
                ),
                ("landing_schema_at", models.DateTimeField(blank=True, null=True)),
                ("landing_purged_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="django_connectors.connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "binding",
                "verbose_name_plural": "bindings",
                "ordering": ("-created_at",),
                "permissions": (("run_binding", "Can trigger a binding run"),),
            },
        ),
        migrations.CreateModel(
            name="ConnectionSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "encryption",
                    models.CharField(
                        choices=[("none", "Plaintext"), ("fernet", "Fernet")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="django_connectors.connection",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection secret",
                "verbose_name_plural": "connection secrets",
            },
        ),
        migrations.CreateModel(
            name="Projection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource", models.CharField(max_length=150)),
                ("target", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=255)),
                ("mapping", models.JSONField(default=dict)),
                ("filters", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("needs_review", "Needs review"),
                            ("invalid", "Invalid"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projections",
                        to="django_connectors.binding",
                    ),
                ),
            ],
            options={
                "verbose_name": "projection",
                "verbose_name_plural": "projections",
                "ordering": ("-created_at",),
                "permissions": (
                    ("preview_projection", "Can preview a projection"),
                    ("replay_projection", "Can replay a projection"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=django_connectors._uuid._uuid7_fallback,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("scheduled", "Scheduled"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual"),
                            ("backfill", "Backfill"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "dedupe_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dlt_pipeline_name", models.CharField(blank=True, max_length=255)),
                ("dlt_dataset_name", models.CharField(blank=True, max_length=255)),
                ("dlt_load_ids", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_type", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("task_reference", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="django_connectors.binding",
                    ),
                ),
            ],
            options={
                "verbose_name": "run",
                "verbose_name_plural": "runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=django_connectors._uuid._uuid7_fallback,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("incremental", "Incremental"),
                            ("full", "Full replay"),
                            ("preview", "Preview"),
                        ],
                        max_length=32,
                    ),
                ),
                ("projection_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("load_ids", models.JSONField(blank=True, default=list)),
                ("records_seen", models.PositiveBigIntegerField(default=0)),
                ("records_written", models.PositiveBigIntegerField(default=0)),
                ("records_deleted", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="django_connectors.projection",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projection_runs",
                        to="django_connectors.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "projection run",
                "verbose_name_plural": "projection runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("resource", models.CharField(blank=True, max_length=150)),
                ("external_id", models.CharField(blank=True, max_length=500)),
                ("external_resource_id", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("renew_at", models.DateTimeField(blank=True, null=True)),
                ("secret_reference", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions",
                        to="django_connectors.binding",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook subscription",
                "verbose_name_plural": "webhook subscriptions",
                "ordering": ("-created_at",),
                "permissions": (
                    ("renew_webhooksubscription", "Can renew a webhook subscription"),
                ),
            },
        ),
        migrations.CreateModel(
            name="BindingLock",
            fields=[
                (
                    "binding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="lock",
                        serialize=False,
                        to="django_connectors.binding",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "binding lock",
                "verbose_name_plural": "binding locks",
                "indexes": [
                    models.Index(fields=["expires_at"], name="dc_lock_expires_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["owner_content_type", "owner_object_id"],
                name="dc_conn_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["provider", "status"], name="dc_conn_provider_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(fields=["setup_token"], name="dc_conn_setup_token_idx"),
        ),
        migrations.AddIndex(
            model_name="binding",
            index=models.Index(
                fields=["connection", "enabled"], name="dc_bind_conn_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="binding",
            index=models.Index(
                fields=["enabled", "next_run_at"], name="dc_bind_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="binding",
            index=models.Index(fields=["status"], name="dc_bind_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="connectionsecret",
            constraint=models.UniqueConstraint(
                fields=("connection", "key"), name="dc_secret_unique_key"
            ),
        ),
        migrations.AddIndex(
            model_name="projection",
            index=models.Index(
                fields=["binding", "resource", "enabled"], name="dc_proj_binding_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projection",
            index=models.Index(fields=["target"], name="dc_proj_target_idx"),
        ),
        migrations.AddIndex(
            model_name="projection",
            index=models.Index(fields=["status"], name="dc_proj_status_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["binding", "-created_at"], name="dc_run_binding_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["status", "created_at"], name="dc_run_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectionrun",
            index=models.Index(
                fields=["projection", "-created_at"], name="dc_projrun_proj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectionrun",
            index=models.Index(
                fields=["status", "created_at"], name="dc_projrun_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooksubscription",
            index=models.Index(
                fields=["binding", "status"], name="dc_hook_binding_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooksubscription",
            index=models.Index(fields=["status", "renew_at"], name="dc_hook_renew_idx"),
        ),
    ]
