# Generated by Django 6.1 on 2026-09-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_connectors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projection",
            name="on_invalid_record",
            field=models.CharField(
                choices=[
                    ("fail", "Fail the run"),
                    ("skip", "Skip the row and report it"),
                ],
                default="fail",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="projectionrun",
            name="records_skipped",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectionrun",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
