# Generated by Django 6.1 on 2026-08-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.CreateModel(
            name="CrmEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("type", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crm.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "CRM event",
                "verbose_name_plural": "CRM events",
                "ordering": ("-occurred_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "external_id"), name="crm_event_identity"
                    )
                ],
            },
        ),
    ]
